// Presentational report body — shared by the real report page
// (app/report/[id]/page.tsx) and the static sample demo (app/demo/sample/page.tsx).
// Takes assembled ReportData; has no idea whether it came from Postgres or a fixture.

import type { ReportData } from '@/lib/report/mapper'
import FindingCard from '@/components/report/FindingCard'
import ExecutiveSummary from '@/components/report/ExecutiveSummary'
import { sortByPriority } from '@/lib/report/executiveSummary'

type Props = {
  report: ReportData
}

export default function ReportView({ report }: Props) {
  const { assessment, findings, discoveryImpact } = report

  const compliant = findings.filter(f => f.classification === 'compliant')
  const flagged = sortByPriority(findings.filter(f => f.classification !== 'compliant'))

  return (
    <div className="mx-auto max-w-4xl px-6 py-16 flex flex-col gap-10">

      <div className="flex flex-col gap-3 pb-6 border-b border-border">
        <span className="font-mono text-xs uppercase tracking-widest text-accent">
          Regulatory Impact Assessment
        </span>
        <h1 className="font-serif text-3xl sm:text-4xl text-foreground">{assessment.product_name}</h1>
        <p className="text-sm text-muted leading-relaxed">{assessment.description}</p>
        <p className="text-xs text-subtle">
          Assessment <span className="font-mono bg-surface px-1.5 py-0.5 rounded">{assessment.id}</span>
          {' · '}
          {new Date(assessment.created_at).toLocaleDateString()}
        </p>
      </div>

      {findings.length === 0 ? (
        <p className="text-sm text-muted">
          No findings were identified for the applicable regulatory areas.
        </p>
      ) : (
        <ExecutiveSummary findings={findings} discoveryImpact={discoveryImpact} />
      )}

      {flagged.length > 0 && (
        <div className="flex flex-col gap-4">
          <h2 className="text-sm font-semibold text-foreground">Findings requiring attention</h2>
          {flagged.map(finding => (
            <FindingCard key={finding.id} finding={finding} />
          ))}
        </div>
      )}

      {compliant.length > 0 && (
        <div className="flex flex-col gap-4">
          <h2 className="text-sm font-semibold text-foreground">Confirmed compliant</h2>
          {compliant.map(finding => (
            <FindingCard key={finding.id} finding={finding} />
          ))}
        </div>
      )}

      {/* Subtle attribution — shows on the live report, the sample report,
          and the printed/PDF export, since PrintButton just prints this
          same view. Not a watermark: plain text, no overlay, no styling
          that interferes with reading the report itself. */}
      <p className="text-xs text-subtle pt-6 border-t border-border">
        Generated by RegImpact AI · Created by Shriyashish Mishra
      </p>

    </div>
  )
}
